#ifndef LAUNCHER_RUNTIME_TEXT_H
#define LAUNCHER_RUNTIME_TEXT_H
typedef enum {
    LTXT_LANGUAGE_NAME,
    LTXT_NO_RECENT_GAME,
    LTXT_SD_CARD,
    LTXT_NOR_FLASH,
    LTXT_START_SETTINGS,
    LTXT_RECENTLY_PLAYED,
    LTXT_LAST_PLAYED,
    LTXT_FAVOURITES,
    LTXT_SETTINGS_TITLE,
    LTXT_SETTINGS_TIME,
    LTXT_SETTINGS_VIEW_MODE,
    LTXT_SETTINGS_THUMBNAILS,
    LTXT_SETTINGS_SOUNDS,
    LTXT_SETTINGS_LANGUAGE,
    LTXT_SETTINGS_THEME,
    LTXT_SETTINGS_COLOUR,
    LTXT_SETTINGS_BOOT_ENGINE,
    LTXT_SETTINGS_AUTO_SAVE,
    LTXT_SETTINGS_RESUME_LAST,
    LTXT_SETTINGS_START_SCREEN,
    LTXT_SETTINGS_QUICK_START,
    LTXT_SETTINGS_BOOT_MODE,
    LTXT_SETTINGS_MODE_B,
    LTXT_SETTINGS_INGAME_RTC,
    LTXT_SETTINGS_ENABLE_BIOS,
    LTXT_SETTINGS_BACKUP_SAVES,
    LTXT_SETTINGS_HELP,
    LTXT_SETTINGS_ADDON,
    LTXT_ADDON_RESET,
    LTXT_ADDON_RTS,
    LTXT_ADDON_SLEEP,
    LTXT_ADDON_CHEAT,
    LTXT_SETTINGS_SLEEP_HOTKEY,
    LTXT_SETTINGS_ADDON_HOTKEY,
    LTXT_SETTINGS_LED,
    LTXT_LED_MASTER,
    LTXT_LED_BREATH_RED,
    LTXT_LED_BREATH_GREEN,
    LTXT_LED_BREATH_BLUE,
    LTXT_LED_SD_RED,
    LTXT_LED_SD_GREEN,
    LTXT_LED_SD_BLUE,
    LTXT_ON,
    LTXT_OFF,
    LTXT_VIEW_LIST,
    LTXT_VIEW_HORIZONTAL,
    LTXT_VIEW_VERTICAL,
    LTXT_THUMB_TITLE,
    LTXT_THUMB_BOX,
    LTXT_ENGINE_FAST,
    LTXT_ENGINE_MANUAL,
    LTXT_BOOT_CLEAN,
    LTXT_BOOT_ADDON,
    LTXT_BOOT_MENU,
    LTXT_MODE_RUMBLE,
    LTXT_MODE_RAM,
    LTXT_MODE_LINK,
    LTXT_HELP_TITLE,
    LTXT_CONTROLS_TITLE,
    LTXT_CONTROL_A,
    LTXT_CONTROL_B,
    LTXT_CONTROL_DPAD,
    LTXT_CONTROL_START,
    LTXT_CONTROL_SELECT,
    LTXT_CONTROL_HOLD_START,
    LTXT_CONTROL_DOUBLE_SELECT,
    LTXT_CONTROL_QUICK_HOTKEY,
    LTXT_CONTROL_QUICK_ACTION,
    LTXT_STATUS_INIT_ERROR,
    LTXT_STATUS_POWER_OFF,
    LTXT_STATUS_INIT_OK,
    LTXT_STATUS_LOADING,
    LTXT_STATUS_FILE_TOO_BIG,
    LTXT_STATUS_WRITING,
    LTXT_STATUS_SELECT_LATEST,
    LTXT_STATUS_CHECK_SAVE,
    LTXT_STATUS_MAKE_SAVE,
    LTXT_STATUS_CHECK_RTS,
    LTXT_STATUS_MAKE_RTS,
    LTXT_STATUS_CHECK_PATCH,
    LTXT_STATUS_MAKE_PATCH,
    LTXT_STATUS_LOADING_ROM,
    LTXT_STATUS_NO_ROMS,
    LTXT_STATUS_COPYING_ROM,
    LTXT_STATUS_GENERATING_EMU,
    LTXT_STATUS_COPY_SAVE,
    LTXT_STATUS_SAVING,
    LTXT_STATUS_SAVE_LOADED,
    LTXT_STATUS_SAVE_SAVED,
    LTXT_STATUS_FILE_EXISTS,
    LTXT_STATUS_SAVE_NOT_FOUND,
    LTXT_STATUS_NOR_FULL,
    LTXT_ROM_MENU_CLEAN,
    LTXT_ROM_MENU_ADDON,
    LTXT_ROM_MENU_WRITE_NOR,
    LTXT_ROM_MENU_WRITE_NOR_ADDON,
    LTXT_ROM_MENU_SAVE_TYPE,
    LTXT_ROM_MENU_CHEAT,
    LTXT_NOR_MENU_DIRECT,
    LTXT_NOR_MENU_DELETE,
    LTXT_NOR_MENU_FORMAT,
    LTXT_NOR_MENU_LOAD_SAVE,
    LTXT_NOR_MENU_SAVE_SAVE,
    LTXT_ERROR_FOLDER,
    LTXT_ERROR_FILE,
    LTXT_ERROR_SAVER,
    LTXT_ERROR_SAVE,
    LTXT_ERROR_READ_SAVE,
    LTXT_ERROR_MAKE_SAVE,
    LTXT_ERROR_RTS,
    LTXT_TOTAL
} LauncherTextId;
typedef struct { const char *name; u16 stored; const char *text[LTXT_TOTAL]; } LauncherLanguagePack;
static const LauncherLanguagePack launcher_language_packs[] = {
    { "English (UK)", 0xE1E1, {
        "English (UK)",
        "No recent game",
        "SD Card",
        "NOR Flash",
        "Settings",
        "Recently Played",
        "Last played",
        "Favourites",
        "Settings",
        "Time settings",
        "View mode",
        "Thumbnails",
        "Sounds",
        "Language",
        "Theme",
        "Colour",
        "Boot engine",
        "Auto save",
        "Resume last",
        "Start screen",
        "Quick start",
        "Boot mode",
        "Mode B",
        "In-game RTC",
        "Enable BIOS",
        "Backup saves",
        "Help",
        "Addon settings",
        "Reset",
        "RTS",
        "Sleep",
        "Cheat",
        "Sleep hotkey",
        "Addon hotkey",
        "LED settings",
        "LED master",
        "Breath red",
        "Breath green",
        "Breath blue",
        "SD red",
        "SD green",
        "SD blue",
        "On",
        "Off",
        "List",
        "Horizontal",
        "Vertical",
        "Title",
        "Box",
        "Fast",
        "Manual",
        "Clean",
        "Addon",
        "Menu",
        "Rumble",
        "RAM",
        "Link",
        "Help",
        "Controls",
        "A: Accept / Enter",
        "B: Cancel / Back",
        "D-pad / L / R: Navigation",
        "Start (SD): View recents",
        "Select (SD/NOR): Cycle view mode",
        "Hold Start (SD): Delete file",
        "Double tap Select (SD): Set favourite",
        "Hold Quick start hotkey on boot:",
        "Instantly launch last played",
        "Failed to initialize microSD card.",
        "Power off the console.",
        "microSD card initialization successful.",
        "Loading...",
        "The file is too big.",
        "Writing...",
        "Select the lastest",
        "Checking Save Data...",
        "Creating Save Data...",
        "Checking RTS file...",
        "Creating RTS file...",
        "Checking Patch file...",
        "Creating Patch file...",
        "Loading ROM...",
        "No .gba ROMs found!",
        "Copying ROM...",
        "Generating Emulator...",
        "Copy game save?",
        "Saving...",
        ".sav has been loaded",
        ".sav has been saved",
        "Overwrite file?",
        "Can't find .sav file",
        "NOR is full!          ",
        "Clean boot",
        "Boot with addon",
        "Write to NOR clean",
        "Write to NOR with addon",
        "Save type",
        "Cheat",
        "Direct boot",
        "Delete",
        "Format all",
        "Load save data",
        "Save save data",
        "Folder error",
        "File error",
        "SAVER error",
        "Save error",
        "Read save error",
        "Make save error",
        "RTS file error",
    } },
    { "English (US)", 0xE101, {
        "English (US)",
        "No recent game",
        "SD Card",
        "NOR Flash",
        "Settings",
        "Recently Played",
        "Last played",
        "Favorites",
        "Settings",
        "Time settings",
        "View mode",
        "Thumbnails",
        "Sounds",
        "Language",
        "Theme",
        "Color",
        "Boot engine",
        "Auto save",
        "Resume last",
        "Start screen",
        "Quick start",
        "Boot mode",
        "Mode B",
        "In-game RTC",
        "Enable BIOS",
        "Backup saves",
        "Help",
        "Addon settings",
        "Reset",
        "RTS",
        "Sleep",
        "Cheat",
        "Sleep hotkey",
        "Addon hotkey",
        "LED settings",
        "LED master",
        "Breath red",
        "Breath green",
        "Breath blue",
        "SD red",
        "SD green",
        "SD blue",
        "On",
        "Off",
        "List",
        "Horizontal",
        "Vertical",
        "Title",
        "Box",
        "Fast",
        "Manual",
        "Clean",
        "Addon",
        "Menu",
        "Rumble",
        "RAM",
        "Link",
        "Help",
        "Controls",
        "A: Accept / Enter",
        "B: Cancel / Back",
        "D-pad / L / R: Navigation",
        "Start (SD): View recents",
        "Select (SD/NOR): Cycle view mode",
        "Hold Start (SD): Delete file",
        "Double tap Select (SD): Set favorite",
        "Hold Quick start hotkey on boot:",
        "Instantly launch last played",
        "Failed to initialize microSD card.",
        "Power off the console.",
        "microSD card initialization successful.",
        "Loading...",
        "The file is too big.",
        "Writing...",
        "Select the lastest",
        "Checking Save Data...",
        "Creating Save Data...",
        "Checking RTS file...",
        "Creating RTS file...",
        "Checking Patch file...",
        "Creating Patch file...",
        "Loading ROM...",
        "No .gba ROMs found!",
        "Copying ROM...",
        "Generating Emulator...",
        "Copy game save?",
        "Saving...",
        ".sav has been loaded",
        ".sav has been saved",
        "Overwrite file?",
        "Can't find .sav file",
        "NOR is full!          ",
        "Clean boot",
        "Boot with addon",
        "Write to NOR clean",
        "Write to NOR with addon",
        "Save type",
        "Cheat",
        "Direct boot",
        "Delete",
        "Format all",
        "Load save data",
        "Save save data",
        "Folder error",
        "File error",
        "SAVER error",
        "Save error",
        "Read save error",
        "Make save error",
        "RTS file error",
    } },
    { "Espa\303\261ol", 0xE102, {
        "Espa\303\261ol",
        "No hay juego reciente",
        "Tarjeta SD",
        "Flash NOR",
        "Ajustes",
        "Jugados recientes",
        "\303\232ltimo jugado",
        "Favoritos",
        "Ajustes",
        "Hora",
        "Modo de vista",
        "Miniaturas",
        "Sonidos",
        "Idioma",
        "Tema",
        "Color",
        "Motor inicio",
        "Guardado auto",
        "Reanudar",
        "In\303\255cio",
        "In\303\255cio rapido",
        "Modo inicio",
        "Modo B",
        "RTC en juego",
        "Activar BIOS",
        "Copia saves",
        "Ayuda",
        "Ajustes addon",
        "Reinicio",
        "RTS",
        "Reposo",
        "Trucos",
        "Tecla reposo",
        "Tecla addon",
        "Ajustes LED",
        "LED maestro",
        "Pulso rojo",
        "Pulso verde",
        "Pulso azul",
        "SD rojo",
        "SD verde",
        "SD azul",
        "S\303\255",
        "No",
        "Lista",
        "Horizontal",
        "Vertical",
        "T\303\255tulo",
        "Caja",
        "R\303\241pido",
        "Manual",
        "Limpio",
        "Con addon",
        "Menu",
        "Vibraci\303\263n",
        "RAM",
        "Link",
        "Ayuda",
        "Controles",
        "A: Aceptar / Entrar",
        "B: Cancelar / Atras",
        "D-pad / L / R: Navegar",
        "Start (SD): Ver recientes",
        "Select (SD/NOR): Cambiar vista",
        "Mantener Start (SD): Borrar archivo",
        "Doble toque Select (SD): Favorito",
        "Mantener tecla de inicio rapido:",
        "Lanza al instante el ultimo juego",
        "No se pudo iniciar la microSD.",
        "Apaga la consola.",
        "microSD iniciada correctamente.",
        "Cargando...",
        "El archivo es demasiado grande.",
        "Escribiendo...",
        "Selecciona el ultimo",
        "Comprobando partida...",
        "Creando partida...",
        "Comprobando archivo RTS...",
        "Creando archivo RTS...",
        "Comprobando parche...",
        "Creando parche...",
        "Cargando ROM...",
        "No se encontraron ROMs .gba!",
        "Copiando ROM...",
        "Generando emulador...",
        "Copiar partida?",
        "Guardando...",
        ".sav cargado",
        ".sav guardado",
        "Sobrescribir archivo?",
        "No se encuentra .sav",
        "NOR est\303\241 llena!       ",
        "Arranque limpio",
        "Arrancar con addon",
        "Escribir NOR limpio",
        "Escribir NOR con addon",
        "Tipo de guardado",
        "Trucos",
        "Arranque directo",
        "Borrar",
        "Formatear todo",
        "Cargar partida",
        "Guardar partida",
        "Error de carpeta",
        "Error de archivo",
        "Error de SAVER",
        "Error de partida",
        "Error al leer partida",
        "Error al crear partida",
        "Error de archivo RTS",
    } },
    { "Fran\303\247ais", 0xE103, {
        "Fran\303\247ais",
        "Aucun jeu recent",
        "Carte SD",
        "Flash NOR",
        "R\303\251glages",
        "Jeux recents",
        "Dernier jeu",
        "Favoris",
        "R\303\251glages",
        "R\303\251glages heure",
        "Mode affichage",
        "Miniatures",
        "Sons",
        "Langue",
        "Theme",
        "Couleur",
        "Moteur",
        "Save auto",
        "Reprendre",
        "Accueil",
        "D\303\251m. rapide",
        "Mode demarrage",
        "Mode B",
        "RTC en jeu",
        "Activer BIOS",
        "Copie saves",
        "Aide",
        "R\303\251glages addon",
        "Reset",
        "RTS",
        "Veille",
        "Codes",
        "Touche veille",
        "Touche addon",
        "R\303\251glages LED",
        "LED principale",
        "Pulse rouge",
        "Pulse vert",
        "Pulse bleu",
        "SD rouge",
        "SD vert",
        "SD bleu",
        "Oui",
        "Non",
        "Liste",
        "Horizontal",
        "Vertical",
        "Titre",
        "Boite",
        "Rapide",
        "Manuel",
        "Propre",
        "Avec addon",
        "Menu",
        "Vibration",
        "RAM",
        "Lien",
        "Aide",
        "Commandes",
        "A: Valider / Entrer",
        "B: Annuler / Retour",
        "D-pad / L / R: Navigation",
        "Start (SD): Voir recents",
        "Select (SD/NOR): Changer vue",
        "Maintenir Start (SD): Supprimer",
        "Double tap Select (SD): Favori",
        "Maintenir touche demarrage rapide:",
        "Lance aussitot le dernier jeu",
        "Impossible d initialiser la microSD.",
        "Eteignez la console.",
        "microSD initialisee.",
        "Chargement...",
        "Le fichier est trop gros.",
        "Ecriture...",
        "Choisir le dernier",
        "Verification sauvegarde...",
        "Creation sauvegarde...",
        "Verification fichier RTS...",
        "Creation fichier RTS...",
        "Verification patch...",
        "Creation patch...",
        "Chargement ROM...",
        "Aucune ROM .gba trouv\303\251e!",
        "Copie ROM...",
        "Creation emulateur...",
        "Copier sauvegarde?",
        "Sauvegarde...",
        ".sav charge",
        ".sav sauvegarde",
        "\303\211craser fichier?",
        ".sav introuvable",
        "NOR pleine!          ",
        "Demarrage propre",
        "Demarrer avec addon",
        "Ecrire NOR propre",
        "Ecrire NOR avec addon",
        "Type sauvegarde",
        "Codes",
        "Demarrage direct",
        "Supprimer",
        "Tout formater",
        "Charger sauvegarde",
        "Sauver sauvegarde",
        "Erreur dossier",
        "Erreur fichier",
        "Erreur SAVER",
        "Erreur sauvegarde",
        "Erreur lecture sauvegarde",
        "Erreur creation sauvegarde",
        "Erreur fichier RTS",
    } },
    { "Portugu\303\252s", 0xE104, {
        "Portugu\303\252s",
        "Nenhum jogo recente",
        "Cart\303\243o SD",
        "Flash NOR",
        "Defini\303\247\303\265es",
        "Jogados recentes",
        "Ultimo jogado",
        "Favoritos",
        "Defini\303\247\303\265es",
        "Hora",
        "Modo de vista",
        "Miniaturas",
        "Sons",
        "Idioma",
        "Tema",
        "Cor",
        "Motor inicio",
        "Guardar auto",
        "Retomar ultimo",
        "Ecr\303\243 inicial",
        "In\303\255cio rapido",
        "Modo arranque",
        "Modo B",
        "RTC no jogo",
        "Ativar BIOS",
        "Copiar saves",
        "Ajuda",
        "Config addon",
        "Reset",
        "RTS",
        "Suspender",
        "Cheats",
        "Tecla repouso",
        "Tecla addon",
        "Defini\303\247\303\265es LED",
        "LED principal",
        "Pulso vermelho",
        "Pulso verde",
        "Pulso azul",
        "SD vermelho",
        "SD verde",
        "SD azul",
        "Ligado",
        "Desligado",
        "Lista",
        "Horizontal",
        "Vertical",
        "T\303\255tulo",
        "Caixa",
        "R\303\241pido",
        "Manual",
        "Limpo",
        "Com addon",
        "Menu",
        "Vibracao",
        "RAM",
        "Link",
        "Ajuda",
        "Controlos",
        "A: Aceitar / Entrar",
        "B: Cancelar / Voltar",
        "D-pad / L / R: Navegar",
        "Start (SD): Ver recentes",
        "Select (SD/NOR): Mudar vista",
        "Segurar Start (SD): Apagar ficheiro",
        "Duplo toque Select (SD): Favorito",
        "Segurar tecla de inicio rapido:",
        "Lanca logo o ultimo jogo",
        "Falha ao iniciar microSD.",
        "Desliga a consola.",
        "microSD iniciada.",
        "A carregar...",
        "O ficheiro e grande demais.",
        "A escrever...",
        "Seleciona o ultimo",
        "A verificar save...",
        "A criar save...",
        "A verificar RTS...",
        "A criar RTS...",
        "A verificar patch...",
        "A criar patch...",
        "A carregar ROM...",
        "Nenhuma ROM .gba encontrada!",
        "A copiar ROM...",
        "A criar emulador...",
        "Copiar save?",
        "A guardar...",
        ".sav carregado",
        ".sav guardado",
        "Substituir ficheiro?",
        "N\303\243o encontro .sav",
        "NOR cheia!          ",
        "Arranque limpo",
        "Arrancar com addon",
        "Escrever NOR limpo",
        "Escrever NOR com addon",
        "Tipo de save",
        "Cheats",
        "Arranque direto",
        "Apagar",
        "Formatar tudo",
        "Carregar save",
        "Guardar save",
        "Erro de pasta",
        "Erro de ficheiro",
        "Erro SAVER",
        "Erro de save",
        "Erro ao ler save",
        "Erro ao criar save",
        "Erro de ficheiro RTS",
    } },
    { "Deutsch", 0xE105, {
        "Deutsch",
        "Kein letztes Spiel",
        "SD-Karte",
        "NOR-Flash",
        "Einstellungen",
        "Zuletzt gespielt",
        "Letztes Spiel",
        "Favoriten",
        "Einstellungen",
        "Zeit",
        "Ansicht",
        "Vorschaubilder",
        "Sounds",
        "Sprache",
        "Theme",
        "Farbe",
        "Start-Engine",
        "Auto speichern",
        "Fortsetzen",
        "Startseite",
        "Schnellstart",
        "Startmodus",
        "Modus B",
        "RTC im Spiel",
        "BIOS an",
        "Saves sichern",
        "Hilfe",
        "Addon-Setup",
        "Reset",
        "RTS",
        "Standby",
        "Cheats",
        "Standby-Taste",
        "Addon-Taste",
        "LED-Setup",
        "Haupt-LED",
        "Puls rot",
        "Puls gr\303\274n",
        "Puls blau",
        "SD rot",
        "SD gr\303\274n",
        "SD blau",
        "Ein",
        "Aus",
        "Liste",
        "Horizontal",
        "Vertikal",
        "Titel",
        "Box",
        "Schnell",
        "Manuell",
        "Sauber",
        "Mit Addon",
        "Menu",
        "Rumble",
        "RAM",
        "Link",
        "Hilfe",
        "Steuerung",
        "A: Best\303\244tigen / Enter",
        "B: Abbrechen / Zur\303\274ck",
        "D-pad / L / R: Navigation",
        "Start (SD): Letzte anzeigen",
        "Select (SD/NOR): Ansicht wechseln",
        "Start halten (SD): Datei loeschen",
        "Select doppelt (SD): Favorit",
        "Schnellstart-Taste halten:",
        "Startet sofort das letzte Spiel",
        "microSD konnte nicht starten.",
        "Konsole ausschalten.",
        "microSD erfolgreich gestartet.",
        "Laedt...",
        "Datei ist zu gro\303\237.",
        "Schreibt...",
        "Letztes w\303\244hlen",
        "Pr\303\274fe Save-Daten...",
        "Erstelle Save-Daten...",
        "Pr\303\274fe RTS-Datei...",
        "Erstelle RTS-Datei...",
        "Pr\303\274fe Patch-Datei...",
        "Erstelle Patch-Datei...",
        "ROM wird geladen...",
        "Keine .gba ROMs gefunden!",
        "Kopiere ROM...",
        "Erstelle Emulator...",
        "Save kopi\303\253ren?",
        "Speichert...",
        ".sav geladen",
        ".sav gespeichert",
        "Datei ersetzen?",
        ".sav nicht gefunden",
        "NOR ist voll!       ",
        "Sauber starten",
        "Mit Addon starten",
        "Sauber auf NOR",
        "NOR mit Addon",
        "Save-Typ",
        "Cheats",
        "Direkt starten",
        "L\303\266schen",
        "Alles formatieren",
        "Save laden",
        "Save speichern",
        "Ordnerfehler",
        "Dateifehler",
        "SAVER-Fehler",
        "Save-Fehler",
        "Save-Lesefehler",
        "Save-Erstellfehler",
        "RTS-Dateifehler",
    } },
    { "T\303\274rk\303\247e", 0xE106, {
        "T\303\274rk\303\247e",
        "Son oyun yok",
        "SD kart",
        "NOR Flash",
        "Ayarlar",
        "Son oynananlar",
        "Son oynanan",
        "Favoriler",
        "Ayarlar",
        "Saat ayarlari",
        "G\303\266r\303\274n\303\274m modu",
        "K\303\274\303\247\303\274k resimler",
        "Sesler",
        "Dil",
        "Tema",
        "Renk",
        "Ba\305\237lat motoru",
        "Otomatik kay\304\261t",
        "Son oyuna don",
        "Ba\305\237lang\304\261\303\247",
        "H\304\261zl\304\261 ba\305\237lat",
        "Ba\305\237latma modu",
        "Mod B",
        "Oyun ici RTC",
        "BIOS ac",
        "Kay\304\261t yedegi",
        "Yard\304\261m",
        "Addon ayarlari",
        "Reset",
        "RTS",
        "Uyku",
        "Hile",
        "Uyku tu\305\237u",
        "Addon tu\305\237u",
        "LED ayarlari",
        "Ana LED",
        "Nefes kirmizi",
        "Nefes yesil",
        "Nefes mavi",
        "SD kirmizi",
        "SD yesil",
        "SD mavi",
        "A\303\247\304\261k",
        "Kapal\304\261",
        "Liste",
        "Yatay",
        "Dikey",
        "Ba\305\237l\304\261k",
        "Kutu",
        "H\304\261zl\304\261",
        "Manuel",
        "Temiz",
        "Addon ile",
        "Menu",
        "Titre\305\237im",
        "RAM",
        "Link",
        "Yard\304\261m",
        "Kontroller",
        "A: Kabul / Gir",
        "B: \304\260ptal / Geri",
        "D-pad / L / R: Gezinme",
        "Start (SD): Sonlari goster",
        "Select (SD/NOR): G\303\266r\303\274n\303\274m de\304\237i\305\237tir",
        "Start basili (SD): Dosya sil",
        "Select cift tik (SD): Favori",
        "H\304\261zl\304\261 ba\305\237lat tu\305\237unu tut:",
        "Son oyunu an\304\261nda ba\305\237lat",
        "microSD ba\305\237latilamadi.",
        "Konsolu kapat.",
        "microSD ba\305\237latildi.",
        "Y\303\274kleniyor...",
        "Dosya cok b\303\274y\303\274k.",
        "Yaz\304\261l\304\261yor...",
        "Sonuncuyu se\303\247",
        "Kay\304\261t verisi kontrol...",
        "Kay\304\261t verisi olu\305\237tur...",
        "RTS dosyasi kontrol...",
        "RTS dosyasi olu\305\237tur...",
        "Yama dosyasi kontrol...",
        "Yama dosyasi olu\305\237tur...",
        "ROM yukleniyor...",
        ".gba ROM bulunamad\304\261!",
        "ROM kopyalan\304\261yor...",
        "Emulator olu\305\237turuluyor...",
        "Kay\304\261t kopyalansin mi?",
        "Kaydediliyor...",
        ".sav yuklendi",
        ".sav kaydedildi",
        "Dosyanin \303\274st\303\274ne yaz?",
        ".sav bulunamad\304\261",
        "NOR dolu!           ",
        "Temiz ba\305\237lat",
        "Addon ile ba\305\237lat",
        "NOR temiz yaz",
        "NOR addon ile yaz",
        "Kay\304\261t tipi",
        "Hile",
        "Direkt ba\305\237lat",
        "Sil",
        "Hepsini formatla",
        "Kay\304\261t yukle",
        "Kay\304\261t kaydet",
        "Klas\303\266r hatas\304\261",
        "Dosya hatas\304\261",
        "SAVER hatas\304\261",
        "Kay\304\261t hatas\304\261",
        "Kay\304\261t okuma hatas\304\261",
        "Kay\304\261t olu\305\237turma hatas\304\261",
        "RTS dosya hatas\304\261",
    } },
    { "Italiano", 0xE107, {
        "Italiano",
        "Nessun gioco recente",
        "Scheda SD",
        "Flash NOR",
        "Impostazioni",
        "Giocati di recente",
        "Ultimo giocato",
        "Preferiti",
        "Impostazioni",
        "Ora",
        "Modo vista",
        "Miniature",
        "Suoni",
        "Lingua",
        "Tema",
        "Colore",
        "Motore avvio",
        "Auto salva",
        "Riprendi",
        "Schermata",
        "Avvio rapido",
        "Modo avvio",
        "Modo B",
        "RTC in gioco",
        "Abilita BIOS",
        "Backup saves",
        "Aiuto",
        "Opzioni addon",
        "Reset",
        "RTS",
        "Sospensione",
        "Trucchi",
        "Tasto standby",
        "Tasto addon",
        "Opzioni LED",
        "LED principale",
        "Respiro rosso",
        "Respiro verde",
        "Respiro blu",
        "SD rosso",
        "SD verde",
        "SD blu",
        "S\303\254",
        "No",
        "Lista",
        "Orizzontale",
        "Verticale",
        "Titolo",
        "Scatola",
        "Rapido",
        "Manuale",
        "Pulito",
        "Con addon",
        "Menu",
        "Vibrazione",
        "RAM",
        "Link",
        "Aiuto",
        "Comandi",
        "A: Accetta / Entra",
        "B: Annulla / Indietro",
        "D-pad / L / R: Naviga",
        "Start (SD): Vedi recenti",
        "Select (SD/NOR): Cambia vista",
        "Tieni Start (SD): Elimina file",
        "Doppio Select (SD): Preferito",
        "Tieni tasto avvio rapido:",
        "Avvia subito l ultimo gioco",
        "Impossibile avviare microSD.",
        "Spegni la console.",
        "microSD avviata.",
        "Caricamento...",
        "Il file \303\250 troppo grande.",
        "Scrittura...",
        "Scegli l ultimo",
        "Controllo salvataggio...",
        "Creo salvataggio...",
        "Controllo file RTS...",
        "Creo file RTS...",
        "Controllo patch...",
        "Creo patch...",
        "Carico ROM...",
        "Nessuna ROM .gba trovata!",
        "Copio ROM...",
        "Creo emulatore...",
        "Copiare salvataggio?",
        "Salvataggio...",
        ".sav caricato",
        ".sav salvato",
        "Sovrascrivere file?",
        ".sav non trovato",
        "NOR piena!          ",
        "Avvio pulito",
        "Avvia con addon",
        "Scrivi NOR pulito",
        "Scrivi NOR con addon",
        "Tipo salvataggio",
        "Trucchi",
        "Avvio diretto",
        "Elimina",
        "Formatta tutto",
        "Carica salvataggio",
        "Salva salvataggio",
        "Errore cartella",
        "Errore file",
        "Errore SAVER",
        "Errore salvataggio",
        "Errore lettura save",
        "Errore creazione save",
        "Errore file RTS",
    } },
    { "Nederlands", 0xE108, {
        "Nederlands",
        "Geen recent spel",
        "SD-kaart",
        "NOR-flash",
        "Instellingen",
        "Recent gespeeld",
        "Laatst gespeeld",
        "Favorieten",
        "Instellingen",
        "Tijd",
        "Weergave",
        "Miniaturen",
        "Geluiden",
        "Taal",
        "Thema",
        "Kleur",
        "Start-engine",
        "Auto opslaan",
        "Hervatten",
        "Startscherm",
        "Snelstart",
        "Startmodus",
        "Modus B",
        "RTC in spel",
        "BIOS aan",
        "Save backup",
        "Help",
        "Addon opties",
        "Reset",
        "RTS",
        "Slaapstand",
        "Cheats",
        "Slaaptoets",
        "Addon toets",
        "LED opties",
        "Hoofd-LED",
        "Puls rood",
        "Puls groen",
        "Puls blauw",
        "SD rood",
        "SD groen",
        "SD blauw",
        "Aan",
        "Uit",
        "Lijst",
        "Horizontaal",
        "Verticaal",
        "Titel",
        "Doos",
        "Snel",
        "Handmatig",
        "Schoon",
        "Met addon",
        "Menu",
        "Trillen",
        "RAM",
        "Link",
        "Help",
        "Besturing",
        "A: Accepteren / Enter",
        "B: Annuleren / Terug",
        "D-pad / L / R: Navigeren",
        "Start (SD): Recente tonen",
        "Select (SD/NOR): Weergave wisselen",
        "Start houden (SD): Bestand wissen",
        "Dubbel Select (SD): Favoriet",
        "Snelstarttoets houden:",
        "Start meteen het laatste spel",
        "microSD starten mislukt.",
        "Zet de console uit.",
        "microSD gestart.",
        "Laden...",
        "Het bestand is te groot.",
        "Schrijven...",
        "Kies de laatste",
        "Save-data controleren...",
        "Save-data maken...",
        "RTS-bestand controleren...",
        "RTS-bestand maken...",
        "Patch controleren...",
        "Patch maken...",
        "ROM laden...",
        "Geen .gba ROMs gevonden!",
        "ROM kopi\303\253ren...",
        "Emulator maken...",
        "Save kopi\303\253ren?",
        "Opslaan...",
        ".sav geladen",
        ".sav opgeslagen",
        "Bestand overschrijven?",
        ".sav niet gevonden",
        "NOR is vol!         ",
        "Schoon starten",
        "Start met addon",
        "Schoon naar NOR",
        "NOR met addon",
        "Save-type",
        "Cheats",
        "Direct starten",
        "Wissen",
        "Alles formatteren",
        "Save laden",
        "Save opslaan",
        "Mapfout",
        "Bestandsfout",
        "SAVER-fout",
        "Save-fout",
        "Save leesfout",
        "Save maakfout",
        "RTS-bestandsfout",
    } },
    { "Svenska", 0xE109, {
        "Svenska",
        "Inget nytt spel",
        "SD-kort",
        "NOR-flash",
        "Inst\303\244llningar",
        "Senast spelade",
        "Senast spelat",
        "Favoriter",
        "Inst\303\244llningar",
        "Tid",
        "Visningsl\303\244ge",
        "Miniatyrer",
        "Ljud",
        "Spr\303\245k",
        "Tema",
        "F\303\244rg",
        "Startmotor",
        "Autospara",
        "Forts\303\244tt",
        "Startsk\303\244rm",
        "Snabbstart",
        "Startl\303\244ge",
        "L\303\244ge B",
        "RTC i spel",
        "BIOS p\303\245",
        "Backup saves",
        "Hj\303\244lp",
        "Addon-val",
        "Reset",
        "RTS",
        "Sleep",
        "Cheat",
        "Viloknapp",
        "Addonknapp",
        "LED-val",
        "LED master",
        "Breath red",
        "Breath green",
        "Breath blue",
        "SD red",
        "SD green",
        "SD blue",
        "P\303\245",
        "Av",
        "Lista",
        "Horisontell",
        "Vertikal",
        "Titel",
        "Box",
        "Snabb",
        "Manuell",
        "Ren",
        "Med addon",
        "Meny",
        "Rumble",
        "RAM",
        "Link",
        "Hj\303\244lp",
        "Kontroller",
        "A: Accept / Enter",
        "B: Cancel / Back",
        "D-pad / L / R: Navigation",
        "Start (SD): View recents",
        "Select (SD/NOR): Cycle view mode",
        "Hold Start (SD): Delete file",
        "Double tap Select (SD): Set favourite",
        "Hold Quick start hotkey on boot:",
        "Instantly launch last played",
        "Failed to initialize microSD card.",
        "Power off the console.",
        "microSD card initialization successful.",
        "Laddar...",
        "The file is too big.",
        "Skriver...",
        "Select the lastest",
        "Checking Save Data...",
        "Creating Save Data...",
        "Checking RTS file...",
        "Creating RTS file...",
        "Checking Patch file...",
        "Creating Patch file...",
        "Loading ROM...",
        "Inga .gba ROMs hittades!",
        "Copying ROM...",
        "Generating Emulator...",
        "Copy game save?",
        "Saving...",
        ".sav has been loaded",
        ".sav has been saved",
        "Overwrite file?",
        "Can't find .sav file",
        "NOR \303\244r fullt!       ",
        "Clean boot",
        "Boot with addon",
        "Write to NOR clean",
        "Write to NOR with addon",
        "Save type",
        "Cheat",
        "Direct boot",
        "Delete",
        "Format all",
        "Load save data",
        "Save save data",
        "Folder error",
        "File error",
        "SAVER error",
        "Save error",
        "Read save error",
        "Make save error",
        "RTS file error",
    } },
    { "Suomi", 0xE10A, {
        "Suomi",
        "Ei viime peli\303\244",
        "SD-kortti",
        "NOR-flash",
        "Asetukset",
        "Viimeksi pelatut",
        "Viimeksi pelattu",
        "Suosikit",
        "Asetukset",
        "Aika",
        "N\303\244kym\303\244",
        "Pikkukuvat",
        "\303\204\303\244net",
        "Kieli",
        "Teema",
        "V\303\244ri",
        "K\303\244ynnistin",
        "Autosave",
        "Jatka",
        "Aloitus",
        "Pikak\303\244ynn.",
        "K\303\244ynn. tila",
        "Tila B",
        "RTC peliss\303\244",
        "BIOS p\303\244\303\244lle",
        "Backup saves",
        "Ohje",
        "Addon-valinnat",
        "Reset",
        "RTS",
        "Sleep",
        "Cheat",
        "Unin\303\244pp\303\244in",
        "Addon-n\303\244pp\303\244in",
        "LED-valinnat",
        "LED master",
        "Breath red",
        "Breath green",
        "Breath blue",
        "SD red",
        "SD green",
        "SD blue",
        "P\303\244\303\244ll\303\244",
        "Pois",
        "Lista",
        "Vaaka",
        "Pysty",
        "Nimi",
        "Kotelo",
        "Nopea",
        "Manuaali",
        "Puhdas",
        "Addonilla",
        "Valikko",
        "Rumble",
        "RAM",
        "Link",
        "Ohje",
        "Ohjaus",
        "A: Accept / Enter",
        "B: Cancel / Back",
        "D-pad / L / R: Navigation",
        "Start (SD): View recents",
        "Select (SD/NOR): Cycle view mode",
        "Hold Start (SD): Delete file",
        "Double tap Select (SD): Set favourite",
        "Hold Quick start hotkey on boot:",
        "Instantly launch last played",
        "Failed to initialize microSD card.",
        "Power off the console.",
        "microSD card initialization successful.",
        "Ladataan...",
        "The file is too big.",
        "Kirjoitetaan...",
        "Select the lastest",
        "Checking Save Data...",
        "Creating Save Data...",
        "Checking RTS file...",
        "Creating RTS file...",
        "Checking Patch file...",
        "Creating Patch file...",
        "Loading ROM...",
        ".gba ROMeja ei l\303\266ytynyt!",
        "Copying ROM...",
        "Generating Emulator...",
        "Copy game save?",
        "Saving...",
        ".sav has been loaded",
        ".sav has been saved",
        "Overwrite file?",
        "Can't find .sav file",
        "NOR on t\303\244ynn\303\244!       ",
        "Clean boot",
        "Boot with addon",
        "Write to NOR clean",
        "Write to NOR with addon",
        "Save type",
        "Cheat",
        "Direct boot",
        "Delete",
        "Format all",
        "Load save data",
        "Save save data",
        "Folder error",
        "File error",
        "SAVER error",
        "Save error",
        "Read save error",
        "Make save error",
        "RTS file error",
    } },
    { "\326\320\316\304", 0xE2E2, {
        "\326\320\316\304",
        "\303\273\323\320\327\356\275\374\323\316\317\267",
        "SD\277\250",
        "NOR\311\301\264\346",
        "Settings",
        "\327\356\275\374\323\316\317\267",
        "\327\356\275\374\323\316\317\267",
        "\312\325\262\330",
        "\311\350\326\303",
        "\312\261\274\344",
        "\312\323\315\274\304\243\312\275",
        "\313\365\302\324\315\274",
        "\311\371\322\364",
        "\323\357\321\324",
        "\326\367\314\342",
        "\321\325\311\253",
        "\306\364\266\257\322\375\307\346",
        "\327\324\266\257\261\243\264\346",
        "\274\314\320\370\311\317\264\316",
        "\277\252\312\274\273\255\303\346",
        "\277\354\313\331\306\364\266\257",
        "\306\364\266\257\304\243\312\275",
        "\304\243\312\275B",
        "\323\316\317\267\312\261\326\323",
        "\306\364\323\303BIOS",
        "\261\270\267\335\264\346\265\265",
        "\260\357\326\372",
        "\262\345\274\376\311\350\326\303",
        "\270\264\316\273",
        "\274\264\312\261\264\346\265\265",
        "\313\257\303\337",
        "\275\360\312\326\326\270",
        "\313\257\303\337\310\310\274\374",
        "\262\345\274\376\310\310\274\374",
        "LED\311\350\326\303",
        "LED\327\334\277\252\271\330",
        "\272\364\316\374\272\354",
        "\272\364\316\374\302\314",
        "\272\364\316\374\300\266",
        "SD\272\354",
        "SD\302\314",
        "SD\300\266",
        "\277\252",
        "\271\330",
        "\301\320\261\355",
        "\272\341\317\362",
        "\327\335\317\362",
        "\261\352\314\342",
        "\272\320\315\274",
        "\277\354\313\331",
        "\312\326\266\257",
        "\264\277\276\273",
        "\262\345\274\376",
        "\262\313\265\245",
        "\325\360\266\257",
        "\304\332\264\346",
        "\301\252\273\372",
        "\260\357\326\372",
        "\277\330\326\306",
        "A: \310\267\266\250 / \275\370\310\353",
        "B: \310\241\317\373 / \267\265\273\330",
        "\267\275\317\362\274\374 / L / R: \265\274\272\275",
        "Start (SD): \262\351\277\264\327\356\275\374",
        "Select: \307\320\273\273\312\323\315\274",
        "\260\264\327\241Start: \311\276\263\375\316\304\274\376",
        "\313\253\273\367Select: \311\350\316\252\312\325\262\330",
        "\277\252\273\372\260\264\327\241\277\354\313\331\306\364\266\257\274\374:",
        "\301\242\274\264\306\364\266\257\311\317\264\316\323\316\317\267",
        "Failed to initialize microSD card.",
        "Power off the console.",
        "microSD card initialization successful.",
        "\274\323\324\330\326\320...",
        "The file is too big.",
        "\320\264\310\353\326\320...",
        "Select the lastest",
        "Checking Save Data...",
        "Creating Save Data...",
        "Checking RTS file...",
        "Creating RTS file...",
        "Checking Patch file...",
        "Creating Patch file...",
        "Loading ROM...",
        "\325\322\262\273\265\275.gba\316\304\274\376!",
        "Copying ROM...",
        "Generating Emulator...",
        "Copy game save?",
        "Saving...",
        ".sav has been loaded",
        ".sav has been saved",
        "Overwrite file?",
        "Can't find .sav file",
        "NOR\322\321\302\372!          ",
        "\264\277\276\273\306\364\266\257",
        "\262\345\274\376\306\364\266\257",
        "\320\264\310\353NOR\264\277\276\273",
        "\320\264\310\353NOR\262\345\274\376",
        "\264\346\265\265\300\340\320\315",
        "\275\360\312\326\326\270",
        "\326\261\275\323\306\364\266\257",
        "\311\276\263\375",
        "\310\253\262\277\270\361\312\275\273\257",
        "\274\323\324\330\264\346\265\265",
        "\261\243\264\346\264\346\265\265",
        "Folder error",
        "File error",
        "SAVER error",
        "Save error",
        "Read save error",
        "Make save error",
        "RTS file error",
    } },
};
#define LAUNCHER_LANGUAGE_COUNT (sizeof(launcher_language_packs) / sizeof(launcher_language_packs[0]))
#undef DSTEXT_LANGUAGE_NAME
#undef DSTEXT_NO_RECENT_GAME
#undef DSTEXT_SD_CARD
#undef DSTEXT_NOR_FLASH
#undef DSTEXT_START_SETTINGS
#undef DSTEXT_RECENTLY_PLAYED
#undef DSTEXT_LAST_PLAYED
#undef DSTEXT_FAVOURITES
#undef DSTEXT_SETTINGS_TITLE
#undef DSTEXT_SETTINGS_TIME
#undef DSTEXT_SETTINGS_VIEW_MODE
#undef DSTEXT_SETTINGS_THUMBNAILS
#undef DSTEXT_SETTINGS_SOUNDS
#undef DSTEXT_SETTINGS_LANGUAGE
#undef DSTEXT_SETTINGS_THEME
#undef DSTEXT_SETTINGS_COLOUR
#undef DSTEXT_SETTINGS_BOOT_ENGINE
#undef DSTEXT_SETTINGS_AUTO_SAVE
#undef DSTEXT_SETTINGS_RESUME_LAST
#undef DSTEXT_SETTINGS_START_SCREEN
#undef DSTEXT_SETTINGS_QUICK_START
#undef DSTEXT_SETTINGS_BOOT_MODE
#undef DSTEXT_SETTINGS_MODE_B
#undef DSTEXT_SETTINGS_INGAME_RTC
#undef DSTEXT_SETTINGS_ENABLE_BIOS
#undef DSTEXT_SETTINGS_BACKUP_SAVES
#undef DSTEXT_SETTINGS_HELP
#undef DSTEXT_SETTINGS_ADDON
#undef DSTEXT_ADDON_RESET
#undef DSTEXT_ADDON_RTS
#undef DSTEXT_ADDON_SLEEP
#undef DSTEXT_ADDON_CHEAT
#undef DSTEXT_SETTINGS_SLEEP_HOTKEY
#undef DSTEXT_SETTINGS_ADDON_HOTKEY
#undef DSTEXT_SETTINGS_LED
#undef DSTEXT_LED_MASTER
#undef DSTEXT_LED_BREATH_RED
#undef DSTEXT_LED_BREATH_GREEN
#undef DSTEXT_LED_BREATH_BLUE
#undef DSTEXT_LED_SD_RED
#undef DSTEXT_LED_SD_GREEN
#undef DSTEXT_LED_SD_BLUE
#undef DSTEXT_ON
#undef DSTEXT_OFF
#undef DSTEXT_VIEW_LIST
#undef DSTEXT_VIEW_HORIZONTAL
#undef DSTEXT_VIEW_VERTICAL
#undef DSTEXT_THUMB_TITLE
#undef DSTEXT_THUMB_BOX
#undef DSTEXT_ENGINE_FAST
#undef DSTEXT_ENGINE_MANUAL
#undef DSTEXT_BOOT_CLEAN
#undef DSTEXT_BOOT_ADDON
#undef DSTEXT_BOOT_MENU
#undef DSTEXT_MODE_RUMBLE
#undef DSTEXT_MODE_RAM
#undef DSTEXT_MODE_LINK
#undef DSTEXT_HELP_TITLE
#undef DSTEXT_CONTROLS_TITLE
#undef DSTEXT_CONTROL_A
#undef DSTEXT_CONTROL_B
#undef DSTEXT_CONTROL_DPAD
#undef DSTEXT_CONTROL_START
#undef DSTEXT_CONTROL_SELECT
#undef DSTEXT_CONTROL_HOLD_START
#undef DSTEXT_CONTROL_DOUBLE_SELECT
#undef DSTEXT_CONTROL_QUICK_HOTKEY
#undef DSTEXT_CONTROL_QUICK_ACTION
#undef DSTEXT_STATUS_INIT_ERROR
#undef DSTEXT_STATUS_POWER_OFF
#undef DSTEXT_STATUS_INIT_OK
#undef DSTEXT_STATUS_LOADING
#undef DSTEXT_STATUS_FILE_TOO_BIG
#undef DSTEXT_STATUS_WRITING
#undef DSTEXT_STATUS_SELECT_LATEST
#undef DSTEXT_STATUS_CHECK_SAVE
#undef DSTEXT_STATUS_MAKE_SAVE
#undef DSTEXT_STATUS_CHECK_RTS
#undef DSTEXT_STATUS_MAKE_RTS
#undef DSTEXT_STATUS_CHECK_PATCH
#undef DSTEXT_STATUS_MAKE_PATCH
#undef DSTEXT_STATUS_LOADING_ROM
#undef DSTEXT_STATUS_NO_ROMS
#undef DSTEXT_STATUS_COPYING_ROM
#undef DSTEXT_STATUS_GENERATING_EMU
#undef DSTEXT_STATUS_COPY_SAVE
#undef DSTEXT_STATUS_SAVING
#undef DSTEXT_STATUS_SAVE_LOADED
#undef DSTEXT_STATUS_SAVE_SAVED
#undef DSTEXT_STATUS_FILE_EXISTS
#undef DSTEXT_STATUS_SAVE_NOT_FOUND
#undef DSTEXT_STATUS_NOR_FULL
#undef DSTEXT_ROM_MENU_CLEAN
#undef DSTEXT_ROM_MENU_ADDON
#undef DSTEXT_ROM_MENU_WRITE_NOR
#undef DSTEXT_ROM_MENU_WRITE_NOR_ADDON
#undef DSTEXT_ROM_MENU_SAVE_TYPE
#undef DSTEXT_ROM_MENU_CHEAT
#undef DSTEXT_NOR_MENU_DIRECT
#undef DSTEXT_NOR_MENU_DELETE
#undef DSTEXT_NOR_MENU_FORMAT
#undef DSTEXT_NOR_MENU_LOAD_SAVE
#undef DSTEXT_NOR_MENU_SAVE_SAVE
#undef DSTEXT_ERROR_FOLDER
#undef DSTEXT_ERROR_FILE
#undef DSTEXT_ERROR_SAVER
#undef DSTEXT_ERROR_SAVE
#undef DSTEXT_ERROR_READ_SAVE
#undef DSTEXT_ERROR_MAKE_SAVE
#undef DSTEXT_ERROR_RTS
#define DSTEXT_LANGUAGE_NAME Launcher_Text(LTXT_LANGUAGE_NAME)
#define DSTEXT_NO_RECENT_GAME Launcher_Text(LTXT_NO_RECENT_GAME)
#define DSTEXT_SD_CARD Launcher_Text(LTXT_SD_CARD)
#define DSTEXT_NOR_FLASH Launcher_Text(LTXT_NOR_FLASH)
#define DSTEXT_START_SETTINGS Launcher_Text(LTXT_START_SETTINGS)
#define DSTEXT_RECENTLY_PLAYED Launcher_Text(LTXT_RECENTLY_PLAYED)
#define DSTEXT_LAST_PLAYED Launcher_Text(LTXT_LAST_PLAYED)
#define DSTEXT_FAVOURITES Launcher_Text(LTXT_FAVOURITES)
#define DSTEXT_SETTINGS_TITLE Launcher_Text(LTXT_SETTINGS_TITLE)
#define DSTEXT_SETTINGS_TIME Launcher_Text(LTXT_SETTINGS_TIME)
#define DSTEXT_SETTINGS_VIEW_MODE Launcher_Text(LTXT_SETTINGS_VIEW_MODE)
#define DSTEXT_SETTINGS_THUMBNAILS Launcher_Text(LTXT_SETTINGS_THUMBNAILS)
#define DSTEXT_SETTINGS_SOUNDS Launcher_Text(LTXT_SETTINGS_SOUNDS)
#define DSTEXT_SETTINGS_LANGUAGE Launcher_Text(LTXT_SETTINGS_LANGUAGE)
#define DSTEXT_SETTINGS_THEME Launcher_Text(LTXT_SETTINGS_THEME)
#define DSTEXT_SETTINGS_COLOUR Launcher_Text(LTXT_SETTINGS_COLOUR)
#define DSTEXT_SETTINGS_BOOT_ENGINE Launcher_Text(LTXT_SETTINGS_BOOT_ENGINE)
#define DSTEXT_SETTINGS_AUTO_SAVE Launcher_Text(LTXT_SETTINGS_AUTO_SAVE)
#define DSTEXT_SETTINGS_RESUME_LAST Launcher_Text(LTXT_SETTINGS_RESUME_LAST)
#define DSTEXT_SETTINGS_START_SCREEN Launcher_Text(LTXT_SETTINGS_START_SCREEN)
#define DSTEXT_SETTINGS_QUICK_START Launcher_Text(LTXT_SETTINGS_QUICK_START)
#define DSTEXT_SETTINGS_BOOT_MODE Launcher_Text(LTXT_SETTINGS_BOOT_MODE)
#define DSTEXT_SETTINGS_MODE_B Launcher_Text(LTXT_SETTINGS_MODE_B)
#define DSTEXT_SETTINGS_INGAME_RTC Launcher_Text(LTXT_SETTINGS_INGAME_RTC)
#define DSTEXT_SETTINGS_ENABLE_BIOS Launcher_Text(LTXT_SETTINGS_ENABLE_BIOS)
#define DSTEXT_SETTINGS_BACKUP_SAVES Launcher_Text(LTXT_SETTINGS_BACKUP_SAVES)
#define DSTEXT_SETTINGS_HELP Launcher_Text(LTXT_SETTINGS_HELP)
#define DSTEXT_SETTINGS_ADDON Launcher_Text(LTXT_SETTINGS_ADDON)
#define DSTEXT_ADDON_RESET Launcher_Text(LTXT_ADDON_RESET)
#define DSTEXT_ADDON_RTS Launcher_Text(LTXT_ADDON_RTS)
#define DSTEXT_ADDON_SLEEP Launcher_Text(LTXT_ADDON_SLEEP)
#define DSTEXT_ADDON_CHEAT Launcher_Text(LTXT_ADDON_CHEAT)
#define DSTEXT_SETTINGS_SLEEP_HOTKEY Launcher_Text(LTXT_SETTINGS_SLEEP_HOTKEY)
#define DSTEXT_SETTINGS_ADDON_HOTKEY Launcher_Text(LTXT_SETTINGS_ADDON_HOTKEY)
#define DSTEXT_SETTINGS_LED Launcher_Text(LTXT_SETTINGS_LED)
#define DSTEXT_LED_MASTER Launcher_Text(LTXT_LED_MASTER)
#define DSTEXT_LED_BREATH_RED Launcher_Text(LTXT_LED_BREATH_RED)
#define DSTEXT_LED_BREATH_GREEN Launcher_Text(LTXT_LED_BREATH_GREEN)
#define DSTEXT_LED_BREATH_BLUE Launcher_Text(LTXT_LED_BREATH_BLUE)
#define DSTEXT_LED_SD_RED Launcher_Text(LTXT_LED_SD_RED)
#define DSTEXT_LED_SD_GREEN Launcher_Text(LTXT_LED_SD_GREEN)
#define DSTEXT_LED_SD_BLUE Launcher_Text(LTXT_LED_SD_BLUE)
#define DSTEXT_ON Launcher_Text(LTXT_ON)
#define DSTEXT_OFF Launcher_Text(LTXT_OFF)
#define DSTEXT_VIEW_LIST Launcher_Text(LTXT_VIEW_LIST)
#define DSTEXT_VIEW_HORIZONTAL Launcher_Text(LTXT_VIEW_HORIZONTAL)
#define DSTEXT_VIEW_VERTICAL Launcher_Text(LTXT_VIEW_VERTICAL)
#define DSTEXT_THUMB_TITLE Launcher_Text(LTXT_THUMB_TITLE)
#define DSTEXT_THUMB_BOX Launcher_Text(LTXT_THUMB_BOX)
#define DSTEXT_ENGINE_FAST Launcher_Text(LTXT_ENGINE_FAST)
#define DSTEXT_ENGINE_MANUAL Launcher_Text(LTXT_ENGINE_MANUAL)
#define DSTEXT_BOOT_CLEAN Launcher_Text(LTXT_BOOT_CLEAN)
#define DSTEXT_BOOT_ADDON Launcher_Text(LTXT_BOOT_ADDON)
#define DSTEXT_BOOT_MENU Launcher_Text(LTXT_BOOT_MENU)
#define DSTEXT_MODE_RUMBLE Launcher_Text(LTXT_MODE_RUMBLE)
#define DSTEXT_MODE_RAM Launcher_Text(LTXT_MODE_RAM)
#define DSTEXT_MODE_LINK Launcher_Text(LTXT_MODE_LINK)
#define DSTEXT_HELP_TITLE Launcher_Text(LTXT_HELP_TITLE)
#define DSTEXT_CONTROLS_TITLE Launcher_Text(LTXT_CONTROLS_TITLE)
#define DSTEXT_CONTROL_A Launcher_Text(LTXT_CONTROL_A)
#define DSTEXT_CONTROL_B Launcher_Text(LTXT_CONTROL_B)
#define DSTEXT_CONTROL_DPAD Launcher_Text(LTXT_CONTROL_DPAD)
#define DSTEXT_CONTROL_START Launcher_Text(LTXT_CONTROL_START)
#define DSTEXT_CONTROL_SELECT Launcher_Text(LTXT_CONTROL_SELECT)
#define DSTEXT_CONTROL_HOLD_START Launcher_Text(LTXT_CONTROL_HOLD_START)
#define DSTEXT_CONTROL_DOUBLE_SELECT Launcher_Text(LTXT_CONTROL_DOUBLE_SELECT)
#define DSTEXT_CONTROL_QUICK_HOTKEY Launcher_Text(LTXT_CONTROL_QUICK_HOTKEY)
#define DSTEXT_CONTROL_QUICK_ACTION Launcher_Text(LTXT_CONTROL_QUICK_ACTION)
#define DSTEXT_STATUS_INIT_ERROR Launcher_Text(LTXT_STATUS_INIT_ERROR)
#define DSTEXT_STATUS_POWER_OFF Launcher_Text(LTXT_STATUS_POWER_OFF)
#define DSTEXT_STATUS_INIT_OK Launcher_Text(LTXT_STATUS_INIT_OK)
#define DSTEXT_STATUS_LOADING Launcher_Text(LTXT_STATUS_LOADING)
#define DSTEXT_STATUS_FILE_TOO_BIG Launcher_Text(LTXT_STATUS_FILE_TOO_BIG)
#define DSTEXT_STATUS_WRITING Launcher_Text(LTXT_STATUS_WRITING)
#define DSTEXT_STATUS_SELECT_LATEST Launcher_Text(LTXT_STATUS_SELECT_LATEST)
#define DSTEXT_STATUS_CHECK_SAVE Launcher_Text(LTXT_STATUS_CHECK_SAVE)
#define DSTEXT_STATUS_MAKE_SAVE Launcher_Text(LTXT_STATUS_MAKE_SAVE)
#define DSTEXT_STATUS_CHECK_RTS Launcher_Text(LTXT_STATUS_CHECK_RTS)
#define DSTEXT_STATUS_MAKE_RTS Launcher_Text(LTXT_STATUS_MAKE_RTS)
#define DSTEXT_STATUS_CHECK_PATCH Launcher_Text(LTXT_STATUS_CHECK_PATCH)
#define DSTEXT_STATUS_MAKE_PATCH Launcher_Text(LTXT_STATUS_MAKE_PATCH)
#define DSTEXT_STATUS_LOADING_ROM Launcher_Text(LTXT_STATUS_LOADING_ROM)
#define DSTEXT_STATUS_NO_ROMS Launcher_Text(LTXT_STATUS_NO_ROMS)
#define DSTEXT_STATUS_COPYING_ROM Launcher_Text(LTXT_STATUS_COPYING_ROM)
#define DSTEXT_STATUS_GENERATING_EMU Launcher_Text(LTXT_STATUS_GENERATING_EMU)
#define DSTEXT_STATUS_COPY_SAVE Launcher_Text(LTXT_STATUS_COPY_SAVE)
#define DSTEXT_STATUS_SAVING Launcher_Text(LTXT_STATUS_SAVING)
#define DSTEXT_STATUS_SAVE_LOADED Launcher_Text(LTXT_STATUS_SAVE_LOADED)
#define DSTEXT_STATUS_SAVE_SAVED Launcher_Text(LTXT_STATUS_SAVE_SAVED)
#define DSTEXT_STATUS_FILE_EXISTS Launcher_Text(LTXT_STATUS_FILE_EXISTS)
#define DSTEXT_STATUS_SAVE_NOT_FOUND Launcher_Text(LTXT_STATUS_SAVE_NOT_FOUND)
#define DSTEXT_STATUS_NOR_FULL Launcher_Text(LTXT_STATUS_NOR_FULL)
#define DSTEXT_ROM_MENU_CLEAN Launcher_Text(LTXT_ROM_MENU_CLEAN)
#define DSTEXT_ROM_MENU_ADDON Launcher_Text(LTXT_ROM_MENU_ADDON)
#define DSTEXT_ROM_MENU_WRITE_NOR Launcher_Text(LTXT_ROM_MENU_WRITE_NOR)
#define DSTEXT_ROM_MENU_WRITE_NOR_ADDON Launcher_Text(LTXT_ROM_MENU_WRITE_NOR_ADDON)
#define DSTEXT_ROM_MENU_SAVE_TYPE Launcher_Text(LTXT_ROM_MENU_SAVE_TYPE)
#define DSTEXT_ROM_MENU_CHEAT Launcher_Text(LTXT_ROM_MENU_CHEAT)
#define DSTEXT_NOR_MENU_DIRECT Launcher_Text(LTXT_NOR_MENU_DIRECT)
#define DSTEXT_NOR_MENU_DELETE Launcher_Text(LTXT_NOR_MENU_DELETE)
#define DSTEXT_NOR_MENU_FORMAT Launcher_Text(LTXT_NOR_MENU_FORMAT)
#define DSTEXT_NOR_MENU_LOAD_SAVE Launcher_Text(LTXT_NOR_MENU_LOAD_SAVE)
#define DSTEXT_NOR_MENU_SAVE_SAVE Launcher_Text(LTXT_NOR_MENU_SAVE_SAVE)
#define DSTEXT_ERROR_FOLDER Launcher_Text(LTXT_ERROR_FOLDER)
#define DSTEXT_ERROR_FILE Launcher_Text(LTXT_ERROR_FILE)
#define DSTEXT_ERROR_SAVER Launcher_Text(LTXT_ERROR_SAVER)
#define DSTEXT_ERROR_SAVE Launcher_Text(LTXT_ERROR_SAVE)
#define DSTEXT_ERROR_READ_SAVE Launcher_Text(LTXT_ERROR_READ_SAVE)
#define DSTEXT_ERROR_MAKE_SAVE Launcher_Text(LTXT_ERROR_MAKE_SAVE)
#define DSTEXT_ERROR_RTS Launcher_Text(LTXT_ERROR_RTS)
#endif
